version: '3'
services:
 db:
  image: mongo
  environment:
    NODE_ENV: development
    MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
    MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
  command: mongod --port 27017
  volumes:
    - beta-mongo-db:/data/db
volumes:
  beta-mongo-db:
