version: '3'
services:
 db:
  image: mongo
  environment:
    NODE_ENV: development
    MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
    MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
  command: mongod --port 27017
  volumes:
    - beta-mongo-db:/data/db
 web:
  image: $CI_REGISTRY_IMAGE:$CI_TAG
  environment:
    MONGO_USER: $MONGO_ROOT_USER
    MONGO_PSWD: $MONGO_ROOT_PASSWORD
    MONGO_URI: db
    MONGO_PORT: 27017
    MONGO_DB: $MONGO_DB
    MONGO_AUTH_DB: admin
    JWT_SECRET: $JWT_SECRET
    JWT_EXPIRY: 30d
  ports:
   - "$NODE_PORT:4000"
  depends_on:
   - db
volumes:
  beta-mongo-db:
