version: '3'
services:
 db:
  image: mongo
  environment:
    NODE_ENV: development
    MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
    MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
  command: mongod --port 27017
  volumes:
    - beta-mongo-db:/data/db
  web:
    image: $CI_REGISTRY_IMAGE:$CI_TAG
    environment:
      MONGO_URI: mongodb://PgFhF8vVZSa3PCPWhw2s8Nns65mhDP3mXhNkjheq:PBVcuCGWkaJn7k6kRCUebUWxGERH3gDpEF4NNpp4xKp2tdQvVrr7phMZJpRtfSC8B5an5g6GWssGcCAFnQxLCW3mCV3pgMGpyEQYuwh2jdGbFKJy7patC2pf3Ca95h2J@db:27017/beta-db?authSource=admin
      NODE_ENV: development
      JWT_SECRET: fVShA9xvrKIB5nJ4TgXEKUjn0tp
      PORT: 4000
    ports:
    - "$NODE_PORT:4000"
    depends_on:
    - db
volumes:
  beta-mongo-db:
