version: '3'
services:
  db:
    image: mongo
    environment:
      NODE_ENV: development
      MONGO_INITDB_ROOT_USERNAME: PgFhF8vVZSa3PCPWhw2s8Nns65mhDP3mXhNkjheq
      MONGO_INITDB_ROOT_PASSWORD: PBVcuCGWkaJn7k6kRCUebUWxGERH3gDpEF4NNpp4xKp2tdQvVrr7phMZJpRtfSC8B5an5g6GWssGcCAFnQxLCW3mCV3pgMGpyEQYuwh2jdGbFKJy7patC2pf3Ca95h2J
    command: mongod --port 27017
    ports:
      - 27017:27017
    volumes:
      - beta-mongo-db:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: PgFhF8vVZSa3PCPWhw2s8Nns65mhDP3mXhNkjheq
      ME_CONFIG_MONGODB_ADMINPASSWORD: PBVcuCGWkaJn7k6kRCUebUWxGERH3gDpEF4NNpp4xKp2tdQvVrr7phMZJpRtfSC8B5an5g6GWssGcCAFnQxLCW3mCV3pgMGpyEQYuwh2jdGbFKJy7patC2pf3Ca95h2J
volumes:
  beta-mongo-db:
